name: Daily Redeploy to Vercel

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook (Forcing No Cache)
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}?buildCache=false"