name: Daily Redeploy to Vercel

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Secret is Set
        run: |
          if [ -z "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            echo "Error: The VERCEL_DEPLOY_HOOK secret is not set or is empty."
            exit 1
          else
            echo "Success: The VERCEL_DEPLOY_HOOK secret is set."
          fi

      - name: Trigger Vercel Deploy Hook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
