name: Daily Video Producer Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  generate-and-upload-video:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant permission to write to the repo
      pull-requests: write # Grant permission to create a Pull Request

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # Enable caching for npm

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for faster, more reliable installs in CI

      - name: Run Video Producer Script
        id: produce_video # Give this step an ID to reference its output
        run: npx tsx scripts/video-producer.ts

      - name: Create Pull Request if files were generated
        uses: peter-evans/create-pull-request@v6
        with:
          # The token is automatically supplied by GitHub Actions
          commit-message: "feat: Generate new video and update database"
          title: "🤖 Daily Video Generation"
          body: |
            New video and database files generated by the Daily Video Producer Bot.
            
            Please review and merge.
          branch: "bot/daily-video-generation" # The bot will create this branch
          delete-branch: true # Automatically delete the branch after the PR is merged
